apiVersion: v1
kind: Service
metadata:
  name: guest-book-service
  labels:
    app: guest-book
spec:
  type: NodePort
  ports:
    - name: guest-book-tcp
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: guest-book
