apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - name: mongodb-tcp
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
